"""note archeved

Revision ID: 07b264752c61
Revises: 9c9816d41837
Create Date: 2022-02-16 19:07:43.031048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b264752c61'
down_revision = '9c9816d41837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'archived')
    # ### end Alembic commands ###
